name: diffutil_sliverlist
description: A SliverList that implicitly animates changes using diffutil.dart.
version: 0.1.0
author: Martin Kamleithner
homepage: https://github.com/knaeckeKami/diffutil_sliverlist

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  diffutil_dart: ^0.1.0
